#!/bin/bash

## in .bash_profile

#SSHAGENT=`which ssh-agent`
#SSHAGENTARGS="-s"
#if [ -z "$SSH_AUTH_SOCK" -a -x "$SSHAGENT" ]; then
#    eval `$SSHAGENT $SSHAGENTARGS`
#    trap "kill $SSH_AGENT_PID" 0
#fi
#
### in .logout
#
#if [ ${SSH_AGENT_PID+1} == 1 ]; then
#    ssh-add -D
#    ssh-agent -k > /dev/null 2>&1
#    unset SSH_AGENT_PID
#    unset SSH_AUTH_SOCK
#fi



pidof ssh-agent to get the IDs

export SSH_AGENT_PID=<pid>
eval `ssh-agent -k`
